<?php

namespace App;

use Nette;
use App\Model;


/**
 * Base presenter for all application presenters.
 */
abstract class BaseSecurePresenter extends BasePresenter
{
	protected function startup()
	{
		parent::startup(); // TODO: Change the autogenerated stub

		if(!$this->user->isLoggedIn()){
			$this->redirect('Sign:in', array('backlink' => $this->storeRequest()));
		}
	}
}
